config/routes.rb
Rails.application.routes.draw do
  root 'words#check_palindrome', as: 'words'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/word.rb
class Word < ApplicationRecord

  def self.generate_random_word
    alphabet = ('a'...'z').to_a
    random_word = (1..5).map { alphabet.sample }.join
    create(name: random_word)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Validator
end

app/controllers/words_controller.rb
class WordsController < ApplicationController


  def check_palindrome
    @word = params[:word]
    @is_palindrome = palindrome?(@word)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TechnicalTestsI</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/words/check_palindrome.html.erb
<h1>Verificador de Palíndromos</h1>

<%= form_with(url: words_path, method: :get) do |f| %>
  <%= f.label :word, 'Digite uma palavra:' %>
  <%= f.text_field :word %>
  <%= submit_tag 'Verificar' %>
<% end %>

<% if defined?@is_palindrome %>
  <p>A palavra "<%= params[:word] %>" é <%= @is_palindrome ? 'um palíndromo' : 'não um palíndromo' %>.</p>
<% end %>